### PR TITLE
Ashenvale Improvements

### PR DESCRIPTION
**Pull request by geo-tp**
Ashenvale
========

**Foulweald**

There are 2 possible models (except ear variation and the named) :  Blue or Brown
Capture d’écran_2022-08-04_06-01-37

Vanilla Foolweald use blue model: 

foolweald
followeald2

So I used blue models for Foulweald mobs, the exact same as vanilla (including ear variation)

**Thistlefur**

Same as Foulweald, there are 2 possible models.

Vanilla Thistlefur use Brown models and white one (not part of 0.5.3)

images_4457

So I used brown models for Thistlefur,  I replaced white one with brown model.

**Xavian & Felmusk**
Satyr models with a lot of color variations are already present in 0.5.3
Capture d’écran_2022-08-04_03-22-35

I used exact same models than 1.12 for each mobs.

**Dark Strand**
Dark strand mobs use 3 different models for each mobs, I updated each Dark Strand mob to remove unavailable display id and add those screenshots show.
Dark Strand Enforcer (Needs Texture)
images_4410
images_4414
images_4441
images_4423

**Wrathtail**
There is only one Naga display_id : 4036. There is no female models yet.
We replace display id of all Ashenvale Nagas mobs with this one. We have screenshot 
that show this display id used at ashenvale location.

janvier2004-51

**Shadethicker Stone mover**
Same as vanilla display_id

**Withered Ancient**
attachments_screenshot_OP04

**Clattering crawler**
Same as vanilla, blue crab. 

**Burning Legionnaire (lesser felguard)**
It appears that Burning legionnaire doesnt exist in 1.12, instead there are Lesser felguard. Probably, this mob was renamed.
Lesser felguard model dosnt exist yet.
Dead Burning Legionnaire
Burning Legionnaire

**Fel slayer**
Dead Fel Slayer

**Mystlash hydra**
Dead Hydra

Notes
====

Here's a screenshot that probably show a part of Ashenvale mobs push 

Capture d’écran_2022-08-04_06-25-04

### CODE REVIEW

**Comment by Yushe** [comment]
Amazing work finding all these correct ids!

**Comment by GrenderG** [comment]
I'm pretty convinced we can safely rename Lesser Felguard to Burning Legionnaire, level range is the same. What do you think @Daribon?

**Comment by Daribon** [comment]
Yes its the same NPC but renamed.
http://web.archive.org/web/20040819074937/http://wow.allakhazam.com/db/mob.html?wmob=3772

**Comment by geo-tp** [comment]
Name is updated.

**Pull request merged**
