### PR TITLE
Teldrassil improvements

### PR DESCRIPTION
**Pull request by geo-tp**
Resolve part of #319. All screenshots mentioned bellow can be found in Alpha Archives, Teldrassil folder.

- **Bloodfeather** 

Bloodfeather type who miss display_id : Rogue, Mattriach, Wind Witch

We have screenshots that show bunch of Bloodfeathers, all with the same display_id (3021).
We also have a screenshot of a Bloodfeather Sorceress with display_id 3021 (1.12 use another display id for this mob)
In 0.5.3, all Bloodfeathers use the same display id, later blizzard will add color variation probably to help players.

- **Gnarlpine**

Gnarlpine type who miss display_id : Warrior, Defender, Ursa, Gardener, Avenger, Pathfinder

We have some screenshots that shows  Gnarlpine (Ambuser, shaman and also a named), all with the same display_id (brown gnarlpine)
Same as Bloodfeathers, in 0.5.3 all Gnarlpine probably use the same display_id and blizzard will update it later. 

- **Nightsaber**

Mangy Nightsaber and Nightsaber probably use display_id 3029, see Daribon comment.

- **Teldrassil Sentinel**

There is only one NE guard model that is not used by a named NPC : 2306. 
It's same model as Darnassus guard and Ashenvale guards. That's probably why Blizzard added more later.
We can see screenshots of Teldrassil Sentinel in Alpha archives, but models are not present in 0.5.3.

- **Zenn Foulhoof**

We have a screenshot

- **Timbering Bark Ripper**

We have a screenshot

### CODE REVIEW

**Comment by Daribon** [comment]
I've looked into Nightsaber and it looks like this on release:
image
Nightsaber Stalker displayid 3030 or young nightsaber 3029 seems to look exactly the same.
There is also 3031, all those 3 displayids are identical.
Nightsaber Stalker on 0.5.3 from alpha-project:
WoWClient_A6d6tmLti7
Young Nightsaber on 0.5.3 from alpha-project:
WoWClient_xWSKE5Soyi

As for the legitimacy of my claims. Just look at displayids that are next to it:
explorer_CLCF08UYsM
Straight Teldrassil displayids.

In regards to the information above, your findings for Gnarlpine and Bloodfeather are accurate.
0.5.5 Bloodfeather Sorceress:
images_2150

When it comes to Teldrassil guards I couldn't find any image of them from pre 0.5.5. The current fix is acceptable and can be changed in the future if other evidence shows up.

While you are at it,
Appears we are using the wrong displayid for Young Thristle Boar.
Displayid 377 seems highly unlikely, when the boar displayids are right between the rest of the Teldrassil displayids.
Young thistle Boar what appears to be an earlier version than 0.5.3:

Here is Young Thistle Boar from past 0.5.5:
ds012
And again from 0.5.5:
image0016
We are likely using displayid from older version than what was available in 0.5.3.

**Comment by geo-tp** [comment]
ill do the change soon.

I also found Aldrassil binder. She is Aelyssa. We can see her new display_id here. 0.5.3 display id is a bit different.

wowbeta_031904_040

creature-display-1914 Aelyssa

**Comment by geo-tp** [comment]
> looks

Nightsaber/mangy nightsaber has no display id right now, that's why I changed it. Ill change for the model your screenshot show.

**Comment by geo-tp** [comment]
Aelyssa is now spawn as Aldrassil binder and Young Thistle Boar now use display_id 3025

**Pull request merged**
