### PR TITLE
Stonetalon Improvements

### PR DESCRIPTION
**Pull request by geo-tp**
Stonetalon
=======

About
------

We mostly need to work on "The Charred Vale", others parts dont missing display_id.

Here's a very clear range of The Charred Vale linked display_id, we can see almost all mobs
images_4476

Rogue flame spirit
---
images_4476

He is the weakest of these fire elems.
fire

We choose 2171

Singed Basilik
-----
images_4493

He's the second of 3 basilik's type
basliks

(Probably there is something wrong with actual first basilik value cause he use 2174 too, probably, blizzard will messed up with scale when this zone get updated, and first basilik will take unused 2174 )

We choose 2174

Vengefull Ancient
----
octobre2003-23

He is the strongest Ancient
treand

We choose 2168

Bloodfury
-----
images_4490
On background
images_4499

Here's the hard part.
Capture d’écran_2022-08-12_00-58-56

We know for sure that Bloodfury use black/red models. We have 6 models and 6 mobs type.
We can see on first screenshot, Harpy is big, probably more than 1.0 scale.

Mobs entries and display_id are linked
Capture d’écran_2022-08-12_01-00-06
Capture d’écran_2022-08-12_00-58-56

We cant rely on scale by level, harpy on screenshot is the weakest mob, but got a big scale.
Harpy is first entry, display_id 2162 with 1.2 scale is first of list. It's seems to match screenshot : 4022 Harpy => 2162.

Since we have no other evidences, best bet is to apply display_id in order :
4023 Roguefeather => 2163
4024 Slayer => 2164
4025 Ambusher => 2165
....

Chimarea
----

There is no chimarea model for 0.5.3.

What model this mob should use ?

### CODE REVIEW

**Comment by GrenderG** [comment]
> There is no chimarea model for 0.5.3.
> 
> What model this mob should use ?

Wind Rider maybe?

**Comment by geo-tp** [comment]
> > There is no chimarea model for 0.5.3.
> > What model this mob should use ?
> 
> Wind Rider maybe?

Probably, we can see 4 models of those but only 3 differents Wind rider in this zone.

**Comment by Daribon** [comment]
May I suggest moving Braelyn Firehand to her correct location?
shyso_5 9_01

Her current spawn location doesn't exist in the 0.5.3 client. Sun Rock Retreat was added in 0.10.0.

Location from screenshot is near worldport 1 2101 1013 229.

A bunch of objects are spawned at the location where Sun Rock Retreat wil later be. If you want you can hide them all. 
worldport 1 949.228 1002.23 103.836

**Comment by geo-tp** [comment]
Fixed

**Comment by GrenderG** [comment]
Will you change the display_id of chimaeras or should I merge this PR already @geo-tp?

**Comment by geo-tp** [comment]
Fixed, Chimaera (4031, 4032) use 2157 (biggest scale) wind rider model.

**Pull request merged**
