### PR TITLE
Tanaris improvements

### PR DESCRIPTION
**Pull request by geo-tp**
Tanaris
======

Scorpid
--------
septembre2004-26

WoWScrnShot_062904_054505
scor

Probably, 3 scorpids type here should use pink model. We use appropriate scale for each level range.

Basilisk
--------
See background, it's probably Gasshide Basilisk
7m_horde_push3_mount_WoWScrnShot_070504_022658
WoWScrnShot_062904_054213

See background, it's probably Gasshide Gazer
WoWScrnShot_062904_054308

Such as scorpids, 3 basilisks type should use same color.
Capture d’écran_2022-08-17_23-19-06
basi

Hazzali (silitidh)
-------
WoWScrnShot_062904_053920
WoWScrnShot_062904_054712
WoWScrnShot_062904_054308

scorpion

We will use those 3 models

Ogre
------
Probably tanaris ogre push
Capture d’écran_2022-08-17_22-35-19
ogre

There are 5 models for 5 mobs type (2casters, 3melee), we use appopriate scale for each level.

Buzzard
--------

There are not a lot red buzzard model (probably 2 with one with a tiny scale).
There is 3 types of buzzards here. We use same model for all. 
Buzzard Roc here already use this display_id.

Dune Smasher
----------
WoWScrnShot_061704_082049

Only one color for giant in 0.5.3, we use default one

Thistlerub Rootshaper
-------
Capture d’écran_2022-08-18_01-11-25

3386 is used by mob next to him, so we use 3385.

Sandfury
------

In vanilla, there are kind of red.

Since we have only 3 colors : red, blue, white, we will use red models.

Hideskinner

Firecaller, Axe thrower (we have evidence show Ace thrower troll with this display_id in STV)

Turtle
-----

There is only one color, we choose a model with 1.2 scale.

Wastewander
------

Should we use old defias models on those ?

Centipaar (silithid)
-----

We can see a green push here (seems to fit Tanaris range)
Capture d’écran_2022-08-17_22-35-38

In vanilla, Hazzali are green and Centipaar are pink. 

There are 2 choices : 
-  All bugs are pink and blizzard will update Centipaar mobs color later
-  Hazzali are pink, Centipaar are green and blizzard will swap color later.

The first seems more logical, but it's not explain why we retrieve 2 green silithids models in tanaris range

Should we use green models or pink models for those bugs ?

Thousand Needle
======

Silithid
------

Change Invader display_id with the good one (mistake on another PR)

### CODE REVIEW

**Comment by GrenderG** [comment]
> Should we use old defias models on those ?

I think we can use them until / if we find more evidence.

Regarding your question about bugs, don't we have both pink and blue/green in 0.5.3?

**Comment by geo-tp** [comment]
Here what bugs models we have : 

PINK
scorpion


GREEN
Capture d’écran_2022-08-17_22-35-38


But like i said, vanilla use Hazzali => GREEN, Centipaar => PINK. We have evidences showing all Hazzali as PINK, 
it doesn't make sense that blizzard reversed the colors of these bugs later, that's why I guess all bugs are PINK for now.

**Comment by GrenderG** [comment]
I see, go ahead and make all bugs pink then @geo-tp!

**Comment by geo-tp** [comment]
It's done.

Centipaar mobs use pink models and Wastewander use old defias.

**Pull request merged**
