### PR TITLE
TODO: Hunter pet trainers 

### PR DESCRIPTION
**Pull request by dirtbikercj**
Closes: #789 with a one exception.

I wasn't able to find a suitable spawn for Nerra, because the reference mob `Radnaal Maneweaver` entry: `6287` is spawned underground and not in the spot he is suppose to be.

Jadenvis Seawatcher
- Updated Subname

Claude Erksine
- Updated Subname
- Updated Display ID

 Grokor
- Updated Subname
- Moved to outside of ogrimmar
- Updated Display id

Harruk
- Updated Subname
- Updated Display id

Rarck
- Updated Subname
- Changed flag
- Spawned at base of tower at sentinel hill
- Updated Display id

krull
- Updated Subname
- Changed flag
- Spawned outside main building at Sen'jin village
- Updated Display id

Alanndarian
- Updated Subname
- Changed flag
- Moved to wildbend river island

Karrina
- Updated Subname
- Updated Display id
- Moved to Loch Modan hunting lodge

Harb 
- Updated Subname
- Changed flag
- Moved to tree shown in screenshot in bloodhoof
- Updated Display id

Jackson Bayne
- Updated Display id
- Spawned in Eastvale logging camp

Rebald Yorglun
- Spawned at Whelgar's Excavation camp - Wetlands

Laer
- Spawned in Mulgore
- Updated Subname
- Changed flag

Zudd
- Updated Subname
- Changed flag

Tursk
- Spawned in Durotar
- Updated Subname
- Changed Flag
- Updated Display id

Frank Ward
- Spawned at Saldean's Farm - Westfall
- Updated display id

Hurom Juggendolf
- Spawned Dun Morogh
- Updated display id

Durdrek Karrin
- Spawned In Dun Morogh
- Updated Display id

Kyln Longclaw
- Spawned Teldrassil - dolaanar
- Updated Subname

Whaldak Darkbenk
- Updated Display id
- Spawned Loch Modan - South Tower

Lanie Reed
- Spawned at Eastvale Logging camp
- Updated Display id

Kysandia
- Spawned in Teldrassil

Talar
-  Spawned in Teldrassil

Henria Derth
- Spawned in Dun Morogh

Bolyun
- Spawned in Darnassus

Brogun
- Not moved, was already in right location

Frank Lasson
- Updated Name
- Updated Subname
- Changed Flag
- Updated Display id
- Moved near Goldshire

Kenna
- Updated Display id
- Updated Name
- Updated Subname
- Updated Flag

Valyen
- Spawned in Darnassus - Cenarion Enclave

Ransin
- Updated Subname
- Updated Flag
- Updated Display id

Galthuk
- Updated Subname
- Updated Flag
- Updated Display id

Nerra
- Not Spawned. See top.

### CODE REVIEW

**Comment by dirtbikercj** [comment]
This PR is ready.

**Comment by geo-tp** [comment]
Grunenstur Balindom is already at right position, he should not be moved

**Comment by dirtbikercj** [comment]
> Grunenstur Balindom is already at right position, he should not be moved

Seen it in devw4rs comment, figured it needed moved. I'll remove it

**Comment by GrenderG** [comment]
Just to confirm, @dirtbikercj, **everything** mentioned in #789 is fixed except the spawn for Nerra?

**Comment by dirtbikercj** [comment]
Need to push 1 commit tomorrow to fix a couple things @geo-tp mentioned to me in a pm, dont merge yet and correct.

**Comment by GrenderG** [comment]
> Need to push 1 commit tomorrow to fix a couple things @geo-tp mentioned to me in a pm, dont merge yet and correct.

Okay!

**Comment by dirtbikercj** [comment]
Harb Display ID also missing as we dont currently know the tauren placeholder at this time

**Comment by GizzleBizzle** [comment]
The placeholder tauren model for deprecated tauren NPCs is 2578

**Comment by dirtbikercj** [comment]
Fantastic, thank you!

**Comment by dirtbikercj** [comment]
Updated with latest information, PR comment updated to reflect.

**Pull request merged**
