### PR TITLE
Quest Parsing From Warcraft Strategy

### PR DESCRIPTION
**Pull request by geo-tp**
Parsed this https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html

with this https://github.com/geo-tp/Alpha-Core-Data-Parser

I decided not to modify the level of the quests, as we cannot determine the min and max player level from the file, that would have been inconsistent

I also cant parse NextQuestId, since there is no way to make a difference from the file with NextQuestInChain field

Hard to check every modifications done

### CODE REVIEW

**Comment by GrenderG** [comment]
Requirements and rewards (items/money) were also checked, right?

**Comment by geo-tp** [comment]
These fields have been excluded : `RewOrReqMoney, NextQuestId, QuestLevel`

`RewOrReqMoney`, because there is no way to make a difference with copper, silver etc from the file, also quest misses it most of the time
`NextQuestId`, there is no way to make a difference with `NextQuestInChain`
`QuestLevel`, file doesnt include player level, so it will be inconsistent if we modify only QuestLevel

Capture d’écran_2023-09-14_22-40-28

**Comment by GrenderG** [comment]
Regarding the money reward I think it follows a pattern: 
- 1 number: copper
- 2 numbers: silver and copper
- 3 numbers (not sure if there's any): gold, silver and copper

Seems like there are 222 quests with a money reward but not sure if many would differ from our current values.

**Comment by geo-tp** [comment]
I'm talking more like this

Capture d’écran_2023-09-14_23-21-30
Capture d’écran_2023-09-14_23-21-48
Capture d’écran_2023-09-14_23-22-06

We could probably determine if it copper or silver with quest level, don't know if this is better than not parsing it

**Comment by geo-tp** [comment]
Checked most and it seems that when there is only one number, it is always silver, so it could be parsed, im gonna add them

**Comment by geo-tp** [comment]
Added them,  silver and copper were mixed when there is only one number but i could avoid that and it should be good

**Pull request merged**
