### PR TITLE
Hunter Reagents added to some vendors

### PR DESCRIPTION
**Pull request by dirtbikercj**
Add Hunter reagents to vendors

-- Frost Vial - 5024
-- Fire tar - 5026
-- Explosive Shell - 5105

-Kimberly Hiett - 789 - FV/FT
https://web.archive.org/web/20050221023547/http://wow.allakhazam.com/db/mob.html?wmob=789

-Keldric Boucher - 1257 FV/FT/ES
https://web.archive.org/web/20041114044125/http://wow.allakhazam.com/db/mob.html?wmob=1257

-Kyra Boucher - 1275 FV/FT/ES
https://web.archive.org/web/20041114005118/http://wow.allakhazam.com/db/mob.html?wmob=1275

-Frederick Stover - 1298 FV/FT/ES
https://web.archive.org/web/20041114012640/http://wow.allakhazam.com/db/mob.html?wmob=1298

-Edwina Monzor - 1462 FV/FT/ES
https://web.archive.org/web/20041114013826/http://wow.allakhazam.com/db/mob.html?wmob=1462

-Falkhaan Isenstrider - 6774 FV/FT/ES
-Creature is ignored
https://web.archive.org/web/20050112161754/http://wow.allakhazam.comdb/mob.html?wmob=6774

Related #428

### CODE REVIEW

**Comment by GrenderG** [comment]
I assume all similar vendors sold them, Horde ones too. What do you think?

**Comment by dirtbikercj** [comment]
I was thinking the same, but have no evidence. I can add some to org/uc for now if you'd like, until we can find more about horde vendors

**Comment by GrenderG** [comment]
All NPCs with subname `Reagent Vendor` should sell the same, so we can add the same https://web.archive.org/web/20040819074441/http://wow.allakhazam.com/db/mob.html?wmob=1275 items to all of them for now.
image


```
+-------+-------------------------------------+----------------+
| entry | name                                | subname        |
+-------+-------------------------------------+----------------+
|  1275 | Kyra Boucher                        | Reagent Vendor |
|  1306 | [UNUSED] Melechan Damodred          | Reagent Vendor |
|  1308 | Owen Vaughn                         | Reagent Vendor |
|  1351 | Brother Cassius                     | Reagent Vendor |
|  1463 | Falkan Armonis                      | Reagent Vendor |
|  1673 | Alyssa Eva                          | Reagent Vendor |
|  3500 | Tarhus                              | Reagent Vendor |
|  3562 | Alaindia                            | Reagent Vendor |
|  3564 | Temp Reagent Vendor Dwarf           | Reagent Vendor |
|  3565 | [UNUSED] Temp Reagent Vendor Undead | Reagent Vendor |
|  3700 | Jadenvis Seawatcher                 | Reagent Vendor |
|  4220 | Cyroen                              | Reagent Vendor |
|  4562 | Thomas Mordan                       | Reagent Vendor |
|  5110 | Barim Jurgenstaad                   | Reagent Vendor |
|  5151 | Ginny Longberry                     | Reagent Vendor |
|  8361 | Chepi                               | Reagent Vendor |
+-------+-------------------------------------+----------------+
```

Some NPCs aren't used or not part of 0.5.3 so just ignore these ones.

**Comment by dirtbikercj** [comment]
Done

**Comment by GrenderG** [comment]
I think it would be better if you completely remove first the `npc_vendor` entries for these NPCs, so they will only have available what's specified in the oldest page of Allakhazam. That way for example Reagent Vendors won't be selling Infernal Stones.

**Comment by dirtbikercj** [comment]
Okay will do, I'm going to close this for now and re-open once im done, as you merged the item ignore changes while i was in the middle of working on this.

**Pull request closed without merging**
