### PR TITLE
Make it so GMs can bypass level requirements for easier debugging.

### PR DESCRIPTION
**Pull request by Yushe**

### CODE REVIEW

**Comment by GrenderG** [comment]
I agree that bypassing level requirements for area triggers for GM accounts is a good idea, but do you think that bypassing the requirement for items is really needed? You can always .level yourself. 🤔

**Comment by Yushe** [comment]
You can't go above the level cap set by the config though so I suggest either allow GMs to bypass level requirements or let GMs use the level command to go above the level cap.

**Comment by GrenderG** [comment]
Good idea, I think these changes make sense:

- Bypass level requirement for area trigger.
- Allow GMs to go above level cap with the level command (I'd still place a hard cap of level 60).

**Comment by GrenderG** [comment]
Did that here: https://github.com/The-Alpha-Project/alpha-core/commit/3a75280caf0591cc4fc2f2546f0392803ab2c797. Thanks a lot for the idea!

**Pull request closed without merging**
