### PR TITLE
TODO: Mulgore Rework 

### PR DESCRIPTION
**Pull request by dirtbikercj**
Will partially address both #695 and #718

#695
[Seer Graytongue](https://db.thealphaproject.eu/index.php?action=show_creature&id=2982&filter=seer&sort_order=name&pos=12&max=18)
- Relocated

[Arra'chea](https://db.thealphaproject.eu/index.php?action=show_creature&id=3058&filter=arra&sort_order=name&pos=1&max=3)
- Changed Display ID to 1230

[Skorn Whitecloud](https://db.thealphaproject.eu/index.php?action=show_creature&id=3052&filter=skorn&sort_order=name&pos=1&max=1)
- Reloacted
- TODO: new gossip text for finishing quest [The Demon Scarred Cloak](https://db.thealphaproject.eu/index.php?action=show_quest&id=770&filter=demon+scarred&sort_order=Title&pos=1&max=1)

[Brave Strongbash](https://db.thealphaproject.eu/index.php?action=show_creature&id=3215&filter=strongbash&sort_order=name&pos=1&max=1)
- Changed shield to [[Monster - Shield, Buckler Wooden]](https://db.thealphaproject.eu/index.php?action=show_item&id=1961&filter=Monster+-+shield&sort_order=name&pos=2&max=10)

[Kar Stormsinger](https://db.thealphaproject.eu/index.php?action=show_creature&id=3690&filter=kar+stormsinger&sort_order=name&pos=1&max=1) and [Harb Clawhoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=3685&filter=Harb&sort_order=name&pos=1&max=1)
- No action needed, these NPC's were re-used as part of the hunter pet trainer update.

[Melor Stonehoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=3441&filter=melor&sort_order=name&pos=1&max=1)
- Changed level to 68
- Changed Display ID to 2578(Placeholder)

[Taloned Swoop's](https://db.thealphaproject.eu/index.php?action=show_creature&id=2971&filter=taloned&sort_order=name&pos=1&max=1)
- Changed Display ID to 388

[Bristleback Shamans](https://db.thealphaproject.eu/index.php?action=show_creature&id=2953&filter=bristleback&sort_order=name&pos=8&max=10)
- Changed Display ID to 1254

[Mull Thunderhorn](https://db.thealphaproject.eu/index.php?action=show_creature&id=2948&filter=Thunderhorn&sort_order=name&pos=5&max=6)
- Relocated

[Flatland Cougars](https://db.thealphaproject.eu/index.php?action=show_creature&id=3035&filter=flatland&sort_order=name&pos=1&max=2)
- Now use [Agonizing Pain](https://db.thealphaproject.eu/index.php?action=show_spell&id=3247&filter=agonizing&sort_order=Name_enUS&pos=1&max=2)

[Prarie Wolves](https://db.thealphaproject.eu/index.php?action=show_creature&id=2958&filter=prairie&sort_order=name&pos=3&max=4) and [Prarie Wolves Alpha](https://db.thealphaproject.eu/index.php?action=show_creature&id=2960&filter=prairie&sort_order=name&pos=4&max=4)
- now use [Threatening Growl](https://db.thealphaproject.eu/index.php?action=show_spell&id=5781&filter=growl&sort_order=Name_enUS&pos=11&max=11)

[Swoops](https://db.thealphaproject.eu/index.php?action=show_creature&id=2970&filter=swoop&sort_order=name&pos=2&max=4)
- now use [Swoop](https://db.thealphaproject.eu/index.php?action=show_spell&id=5708&filter=swoop&sort_order=Name_enUS&pos=1&max=1)

[Palemane Tanners](https://db.thealphaproject.eu/index.php?action=show_creature&id=2949&filter=tanner&sort_order=name&pos=2&max=3)
- now use [Nature's Wrath](https://db.thealphaproject.eu/index.php?action=show_spell&id=5176&filter=wrath&sort_order=Name_enUS&pos=2&max=35)

[Mahnott Roughwound](https://db.thealphaproject.eu/index.php?action=show_creature&id=3077&filter=mahnott&sort_order=name&pos=1&max=1)
- Changed weapon to [[Item Monster - Sword2H, Black Metal Hilt]](https://db.thealphaproject.eu/index.php?action=show_item&id=6224)

[Baine Bloodhoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=2993&filter=baine&sort_order=name&pos=1&max=1)
- Relocated

[Supervisor Fizsprocket](https://db.thealphaproject.eu/index.php?action=show_creature&id=3051)
- Spawned

[Bluffwatcher](https://db.thealphaproject.eu/index.php?action=show_creature&id=3084&filter=bluffwatcher&sort_order=name&pos=1&max=1)
- Now wield [Monster - Axe, 2H Single Bladed](https://db.thealphaproject.eu/index.php?action=show_item&id=5289&filter=monster+-+axe&sort_order=name&pos=3&max=8)

#718
[The hunt begins](https://db.thealphaproject.eu/index.php?action=show_quest&id=747&filter=the+hunt+begins&sort_order=Title&pos=1&max=1)
- Changed required items to 4 each for [plainstrider meat](https://db.thealphaproject.eu/index.php?action=show_item&id=4739) and 4 [plainstrider feathers](https://db.thealphaproject.eu/index.php?action=show_item&id=4740)

[Sharing the land](https://db.thealphaproject.eu/index.php?action=show_quest&id=745&filter=sharing&sort_order=Title&pos=1&max=1)
- Now rewards 1 Silver 35 Copper

[A humble task](https://db.thealphaproject.eu/index.php?action=show_quest&id=752&filter=a+humble+task&sort_order=Title&pos=1&max=3)
- No longer rewards any gold

 Water well cleansing chain
- Only available for Taurens

[Rite of Vision](https://db.thealphaproject.eu/index.php?action=show_quest&id=772)
- TODO: Event

### CODE REVIEW

**Review by geo-tp — CHANGES_REQUESTED** [review]
(Only reviewing display_id choices here)

Ara'chea
--------

Capture d’écran_2023-01-03_19-01-18

1230 is used by other normal Kodo around
1231 is totaly unused
1241 is used by a higher lvl named kodo (barrens)

Other display_id dont realy fit into mulgore range.

Best choice is to use 1231 with 1.2 scale (in mulgore range, scale make sense for a named)

Taloned Swoop
-------
Capture d’écran_2023-01-03_19-00-52

There are 3 types of swoop in Mulgore : Wiry swoop (lowest lvl), Swoop (medium lvl), Taloned swoop (highest lvl)

Capture d’écran_2023-01-03_19-02-46

1228 with 0.75 scale is used by Wiry swoop, 1229 with scale 0.85 is used by Swoop.

Since Taloned swoop is a placeholder model in 0.5.3, using 388 with 1.1 scale seems acceptable even if it's not into Mulgore range. 1229 could be used as well, both choices make sense.


Bristleback
--------

(This one was resolved in my last PR and was removed from this PR)


Request Changes
--------

3058 Arra-chea should use display_id 1231.

**Comment by dirtbikercj** [comment]
I will get this updated, I suck at picking display ID's 😃

**Comment by dirtbikercj** [comment]
Requested change has been made

**Comment by GrenderG** [comment]
Copy-pasting here the pending issues (mobs not casting spells and wrong id convention):

```
They seem to be not working because you need to set the spell list entry in creature_template.spell_list_id
Also, the entries of the creature_spells should have an entry of creature_template.entry * 10
For example a creature with entry 3361 should have its creature_spells.entry set to 33610 
Oh and Flatland Prowler creature entry is 3566, but the update has 3036 for the spell list entry
```

Any update on this @dirtbikercj? I tried to message you on Discord but I can't.

**Comment by GrenderG** [comment]
https://github.com/The-Alpha-Project/alpha-core/commit/4681398372f9aa12bf48395b8d1074e4ee99da7f

**Pull request closed without merging**
