### PR TITLE
Despawn class quests added in 0.5.5

### PR DESCRIPTION
**Pull request by dirtbikercj**
De-spawns Warlock quests, warrior quests, and paladin quests added in 0.5.5
https://wowpedia.fandom.com/wiki/Patch_0.5.5
#398
#405

### CODE REVIEW

**Comment by GrenderG** [comment]
Can you please ignore also quests for other Warlock demons? Thanks!

**Comment by dirtbikercj** [comment]
Whoops forgot those two, done!

**Comment by dirtbikercj** [comment]
Now its done :)

**Comment by GrenderG** [comment]
For the record, there's a Warlock quest that existed in 0.5.3 (`397 | You Have Served Us Well`). I'm gonna skip that one in the class checks and I'll merge. :+1:

**Pull request merged**
