### PR TITLE
Quest Fixes

### LINKED ISSUE #552: [Item/Quest] Incorrect item name and quest objective.
**Describe the bug**
The quest A Recipe for Death (ID 447) asks, among other things, for 6 stacks of Skittering Blood (ID 3254). The name of the item is incorrect, since in 0.5.3 it was called Spider Marrow. The change to Skittering blood was done in the next patch, 0.5.4.
Spider Marrow doesn't exist in the database, so most likely its ID was used for the Skittering blood later on.

**Expected behavior**
Both the quest and the item should display the correct item name of Spider Marrow

**Source**
Official Blizzard Patch-Notes from patch 0.5.4
The exact amount of how many hearts and marrows are needed is still investigated, since the current quantity of 6 is obviously wrong but solid proof is needed to change it.
AF and RfD

### LINKED ISSUE #571: [Quest] Arugal Must Die should have prerequisites.
**Describe the bug**
Arugal must die quest became "prequestless" in patch 0.7, Before that both Prove Your Worth (ID 421) and Arugal's Folly (ID 99) had to be completed before being offered this quest.

**Sources**
(Taken from 0.7 patch notes)
Arugal

### LINKED ISSUE #652: TODO: Rework Mathystra Relics quest
**Describe what needs to be implemented or enhanced**
Server is using the already changed version of [Mathystra Relics](https://classic.wowhead.com/quest=951/mathystra-relics). Blizz changed it when they moved Blackfathom Deeps from Ruins of Mathystra to Zoram Strand in Ashenvale. Several changes need to be made in order to return it to its original form. I've written this report in a way so that different points can be done by multiple people if necessary:

- [ ] **Change the name of Mathystra Relics (Quest ID 951) quest to Blackfathom Relics**

Reasoning
This is the original name of this quest. 

**Source**
First Screenshot

- [ ] **Change the name of [OldBlackfathom MAGIC Relic] (Item ID 5331) to [Blackfathom Relic]**

Reasoning
The original quest required three types of quest items. 2x Mathystra Relic (Item ID 5273), 2x Elven Cup Relic (Item ID 5330) and 2x Blackfathom Relic (Item ID 5331). Only this version of the item survived, so it'll have to be changed into the quest item.

- [ ] **Change [Blackfathom Relic]'s (Item ID 5331) item properties.**

Change item's bonding to 4 - quest
Change maximum stack to 2
Remove the option to sell those items to vendors

Reasoning
Because it's either the old version of Blackfathom Relic, or it was changed over time, those changes need to hapen in order to make it a quest item again. Got data from 

**Source**
First and second screenshot

- [ ] **Change the quest objectives to require 2x Mathystra Relic (Item ID 5273), 2x Elven Cup Relic (Item ID 5330) and 2x Blackfathom Relic (Item ID 5331)**

Reasoning
Those were the original items required for this quest

**Source**
First Screenshot

- [ ] **Add Elven Cup Relic (Item ID 5330) and 2x Blackfathom Relic (Item ID 5331) to game objects' loot tables.**

There are 3 different game objects called Mathystra Relic, that should contain their respective relic quest items. Their IDs are:
13872 (looks like a chalice) should contain an Elven Cup Relic (Item ID 5330) 
12654 (looks like a Night Elf) should contain a Mathystra Relic (Item ID 5273)
13360 (looks like a ball) should contain a Blackfathom Relic (Item ID 5331)

**Source**
Second and third screenshot

- [ ] **Change the text when completing the quest**

Unfortunately the initial quest text is still unaccounted for, possibly lost forever, but the archive contains the text for turning in the quest. I'll spare rewriting it from the fourth screenshot here not to waste anymore space in this lenghty post.

**Source**
Fourth screenshot

**Screenshots**
All from patch 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4459.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4335.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4358.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Darkshore/images_4460.jpg

### PR DESCRIPTION
**Pull request by dirtbikercj**
Closes #552 
Closes #571 
Closes #652 

Note on #652: The rest of the original quest text still needs found and replaced

### CODE REVIEW

**Comment by GrenderG** [comment]
Please also set `NextQuestInChain` to `1014` for quest `99`.

**Comment by GrenderG** [comment]
Please see my comment at https://github.com/The-Alpha-Project/alpha-core/issues/652#issuecomment-1296045248. 

Also, gameobject loot doesn't work like that, `gameobject_loot_template` entry comes from `data1` field of `gameobject_template`. This entry comes from Blizz so shouldn't be changed. You need to check the entries for these 3 gameobjects and just update the `item` field since all 3 already exist.

**Comment by dirtbikercj** [comment]
Ahh okay I see, Ill get these issues corrected.

**Comment by GrenderG** [comment]
> Ahh okay I see, Ill get these issues corrected.

Thanks!

**Pull request closed without merging**
