### PR TITLE
Various fixes and Zone cleanup

### LINKED ISSUE #974: TODO: Change Darkeye bonecaster's Display_ID
[Darkeye Bonecaster](https://db.thealphaproject.eu/index.php?action=show_creature&id=1522&filter=darkeye&sort_order=name&pos=1&max=1)'s Display_ID should either be:
- 200
- 518
- 535
- 732
- 733
- 734
- 775
As they all look the same. Personally I would go for 200,.

**Reasoning**
- the same models, are used by [Rattlecage Soldiers](https://db.thealphaproject.eu/index.php?action=show_creature&id=1520&filter=rattlecage+soldier&sort_order=name&pos=1&max=1) in the same area.
- The size of Display_ID 200 seems to be the same (if not marginally off) with the source material.

It appears, that they're wielding one of the two weapons, that are identical.
- [[Monster - Staff, Basic]](https://db.thealphaproject.eu/index.php?action=show_item&id=1907&filter=monster+-+staff&sort_order=name&pos=3&max=10)
- [[Monster - Staff, Metal /w Spike Crystal]](https://db.thealphaproject.eu/index.php?action=show_item&id=5277&filter=monster+-+staff&sort_order=name&pos=6&max=10)

I would go for [Monster - Staff, Basic]

**Reasoning**
[Monster - Staff, Metal /w Spike Crystal] has much higher ID and itt seems it isn't a finished model, yet (no crystal nor metal elements can be found), probably it was copied to this entry in order to develop it later. Basic weaponry also fits weakest monsters better.

Source (from 0.6)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Tirisfal%20Glades/Pickpocket1.jpg

### LINKED ISSUE #979: TODO: Remove pet trainer duplicates
Two of the pet trainers:
- [Bernie Heisten <Spider Trainer>](https://db.thealphaproject.eu/index.php?action=show_creature&id=3546&filter=trainer&sort_order=name&pos=39&max=446)
- [Bolyun <Spider Trainer>](https://db.thealphaproject.eu/index.php?action=show_creature&id=3698&filter=trainer&sort_order=name&pos=42&max=446)
Have double spawn points. one uncovered by @geo-tp, one from later patches.

**Bernie**
- **Spawn 1** Spawn ID 2703 / Guid 2308 is present in blasted lands (where there aren't any spiders), in a weird position behind nethergarde walls, some distance away from its gold mine.
- **Spawn 2** Spawn ID 400078 / Guid 18824 is standing by the road near Goldshire.

I believe that **Spawn 1** is in this spot because in later patches this NPC was changed to a food and drink vendor in Nethergarde. Since the Nethergarde keep hasn't been changed into its vanilla model yet, he is just standing in place that would eventually become his shop.

**However** both Spawn ID and Guid suggests, that **Spawn 1** is the original NPC, with his spawn-point not artificially added like **Spawn 2**

**Potential solution**
Remove the correct standing **Spawn 2**, move **Spawn 1** into **Spawn 2**'s former place.
This way we can have genuine mob in the correct place.

**Bolyun**
- **Spawn 1** - Spawn ID 32651/ Guid 30474 - This mob is sitting half-buried in a small hill, which is inside the tree, which is high up in inaccesible mountains of southern Ashenvale with an underground campfire to keep him company.
- **Spawn 2** - Spawn ID 400076 / Guid 36767 - This  npc is standing in Darnassus beside the bench with other npcs.

**Spawn 1** is there most likely due to similar situation Bernie had. This area will be eventually changed in the future and Bolyun will be moved there to serve as a general <pet trainer> according to WoWhead.
**Spawn 2**'s general location was confirmed by @geo-tp in #789 as Darnassus, so this one should be used.

**However**, distinguishing which spawn is the original one here is trickier, since both spawns have high Spawn ID and Guid. 

**Potential solution**
I would suggest doing the same thing as with Bernie's spawns - remove **Spawn 2** and move **Spawn 1** into **Spawn 2**'s former place, since lower IDs usually have a higher chance of being genuine. 

Still, the call is Yours.

If You decide to make use of my suggestion, I would also reccomend to take care of **Spawn 1**'s campfire, which is also buried inside inaccesible mountains.

I have archived its details in case we need to restore it, which is very unlikely, but still.
Bolyan's campfire

### LINKED ISSUE #985: TODO:  Gabrielle Chase <Food & Drink> should be located in SW
**Describe what needs to be implemented or enhanced**
3298 Gabrielle Chase is actually located in a unfinished zone, she should stand in Stormwind

https://db.thealphaproject.eu/index.php?action=show_creature&id=3298&sort_order=name&filter_column=display_id1&filter_compare=equals&filter_value=1442&pos=1&max=1

I remember moving Jen Langston thinking it was her on the screenshot, the display_ids are very close(https://displayidbrowser.azurewebsites.net/Human-female). Gabrielle should use Jen Langston's current position

Jen Langston position should be reverted to vanilla one (it's not so needed now that waypoint works, but it will be better)

**Expected end result**
3298 Gabrielle Chase should stand at Jen Langston actual position.
3626 Jen Langston position should be reverted to vanilla one.

### LINKED ISSUE #987: TODO:  Change Claude Erksine display id
**Describe what needs to be implemented or enhanced**

Claude Erksine was missing his display_id, it was changed to old human model because of that screenshot showing another pet trainer wearing it in same area.

187088784-30d1f3f1-8a91-49c8-9792-ff00f66ac0a8

We can see here that Bernie Heinstein and Claude Erksine have linked entry

Capture d’écran_2023-03-17_22-12-14

We can see here Jasyn display_id (3698), Robert display_id (3699) and  Bernie display id (3701)
Capture d’écran_2023-03-17_22-06-28

Except Jason Lemieux (which is an undead), entries and display_id are perfectly linked and 3700 is unused

We know that some pet trainers were human, and were updated to dwarf later, as Aldric Hunter below
321_321_9s

We can also notify how Aldris Hunter's display_id is close to the unused one 3700.

**Expected end result**
3545 Claude Erksine should use display_id 3700

### LINKED ISSUE #988: TODO:  Change Pilot Bellowfiz display_id
wowbeta_031904_027

https://db.thealphaproject.eu/index.php?action=show_creature&filter=pilot&sort_order=name&max=5&pos=1

**Expected end result**
1378 Pilot Bellowfiz should use display_id 3232

### LINKED ISSUE #989: TODO: Spawn Grund Drokda Survivalist
**Describe what needs to be implemented or enhanced**
Capture d’écran_2023-03-17_23-27-15

https://db.thealphaproject.eu/index.php?action=show_creature&id=2756&sort_order=entry&filter_column=entry&filter_compare=in+range&filter_value=2600+TO+2800&pos=144&max=185

Can't find screenshot of him

**Expected end result**
2756 Grund Drokda should be spawned in Dun Morogh

### LINKED ISSUE #994: Client crash fighting a Black Slime
**Describe the bug**
Client crash as seen in the screenshot a few hits into fighting the slime.

**Steps to reproduce**
1. .port -3951.43 -2716.34 27.2922 0 (approximate)
2. find a Black Slime and attack it
3. boom

**Expected behavior**
Shouldn't crash. Seems to be an animation issue maybe?

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mindphluxnet**
Closes #979
Closes #974 
Closes #985 
Closes #987 
Closes #988 
Closes #989 
Closes #994 

### Herbs
- despawn Purple Lotus, this herb was clearly not yet implemented as it has no model, no loot, and isn't pickable
- despawns the herb Arthas's Tears, same as above
- despawns Icecap, same as above
- despawns Blindweed, same as above

### Ironforge

- fix Grumnus Steelshaper's trainer_id to blacksmithing

### Eastern Plaguelands
- removes a (floating) campfire from Light's Hope Chapel, EPL. Reasoning: despite its rather low ID its placement is clearly not matching the terrain. It's also not visible on https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Eastern%20Plaguelands/fb9bf0fd401fcbb4.jpg
- sets the faction for the EPL flight master to Human, Alliance. Reasoning: he's hostile to Horde in the screenshot linked above. Also sets his level to 55+. Reasoning: [see screenshot](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Eastern%20Plaguelands/IMG_EasternPlaugelands.jpg).
- despawn all instances of Rancid Meat/Big Rancid meat. Reasoning: all shane cubes and since EPL isn't remotely done they make no sense here
- despawn Tirion Fordring's Grave/Loose Dirt Mount, reasoning: used by NYI quest "Of Forgotten Memories"
- despawn all parts of Pamela's Doll, reasoning: used by NYI quest "Pamela's Doll"
- despawn all parts of a roadsign north of Darrowshire. Reasoning: the roadsign's post is at a different location and the signs themselves are all shane cubes
- despawn all parts of another roadsign in Corin's Crossing. Reasoning: this time the entire roadsign post is missing and the signs are again all shane cubes
- despawn all gameobjects related to a NYI paladin-only quest called "Exorcising Terrordale". Reasoning: it's NYI, and Terrordale doesn't even exist yet
- despawn Augustus' Receipt Book related to a NYI quest of the same name, reasoning: as above
- despawn all Mark of Detonation gameobjects. Reasoning: NYI quest and the terrain was changed later on so they aren't at their proper location
- despawn Quel'Thalas Registry object. Reasoning: the bench it's supposed to be sitting on is missing, and the quest is NYI

### Winterspring
- despawns loads of gameobjects from Winterspring, including Moontouched Feather and several misc. objects. Reasoning: Winterspring wasn't even remotely done yet, most of it is not terraformed and untextured. These items have no place there yet and most of them are floating in the air or stuck in the ground.

### Searing Gorge
- despawns a few campfires from Searing Gorge. Reasoning: they are clearly from vanilla data. Searing Gorge was opened fairly late and there's nothing there that warrants these campfires to exist. I left in one at a camp site as that one seems plausible.
- move Grisha ```<Binder>``` to Durotar. The "original" was floating in the air in Searing Gorge and the copy was at the correct spot in Durotar so I flipped their location and despawned the Searing Gorge version.
- despawn any gameobject related to the vanilla quests "Trinkets ..." and "The Torch of Retribution". Reasoning: as above, Searing Gorge wasn't open for players in 0.5.3. Even though the IDs are pretty low it makes absolutely no sense for Blizzard to put them there that early, especially since all of them are Shane Cubes. Any screenshots we've got are from way later than 0.5.3. Also, the Torch of Retribution/Light of Retribution objects aren't static spawns either, they get summoned by a script and shouldn't be there.
- despawn two floating objects (Stone Anvil and Forge) from Searing Gorge. Reasoning: due to Searing Gorge not yet complete the terrain doesn't match the object Z so they have no reason to exist yet.
- despawn "Singed Letter" object floating in the air. Reasoning: related to a not yet implemented quest. Also, it's floating in the air so the terrain wasn't done yet.
- despawn "Goodsteel Ledger" object. Reasoning: it's spawned by a quest from the outhouse so it's not a static spawn. The outhouse should probably be removed as well but I wasn't sure about that. The quest doesn't yet exist though so the click handling script effect is missing.

### Azshara
- despawns a Solid Chest standing out in the open. Reasoning: Azshara was unfinished and this chest must have bled in from vanilla where it stood in a camp
- despawn all gameobjects related to the quests "Stealing Knowledge" and "Fragments of the Past". Reasoning: not yet implemented
- despawn Ani, a Shane Cube floating in the ruins. Not even Wowhead knows what this should have been.

### Western Plaguelands
- despawn Redpath's Shield and associated visual effect: Reasoning: vanilla bleed-in, the quest isn't implemented yet

### Silithus
- despawn all gameobjects related to some kind of door between Silithus and the later Ahn'Quiraj. Reasoning: I'm pretty sure this was the door broken down when the gong was rang during the opening event but considering the terrain wasn't even in its final state yet it's more than unlikely these GO's were already there in 0.5.3

### Un'goro Crater
- despawn all Power Crystals, including decorative ones at Marshall's Refuge. Reasoning: they had various uses in vanilla but none of them are already implemented. Un'goro is completely unfinished so it makes no sense to have them spawned already. They also don't have a model yet.

### Felwood
- despawn Corrupted Songflower, Whipper Root, Night  Dragon and Windblossom. Reasoning: all of these corrupted plants could be cleansed using 2x Cenarion Salve for a small XP gain. Each of them have individual quests attached but except for two Windblossoms none of these quests are actually in our database. Not that it would matter as Cenarion Salve is NYI either. All plants have no model.

### Feralas
- despawn several objects (campfire, cauldron) from the area that houses Dire Maul in the future. Reasoning: until Dire Maul was released during vanilla this area was empty except for some animals
- fix Jardenvis Seawatcher to actually be a Crawler Trainer instead of a reagent vendor. Reasoning: he got repurposed as a vendor in vanilla.

### Loch Modan
- fix position of object "Suspicious Barrel" at Stonewrough Dam. Reasoning: terrain changes made this float in the air, it was also not close to the dam's wall any more.

### Wetlands
- set proper placeholder display_id for Dragonmaw Scout. Reasoning: while we don't have any pictures of them they'd likely use the same placeholder display_id as Dragonmaw Grunts (which is used for all other Dragonmaw orcs).
- set movement type for one Dragonmaw Scout's spawn to idle. Reasoning: he uses waypoint movement but due to terrain changes the waypoints don't work and the unit is either running into walls or falling from the sky.
- set faction for Cave Stalker to 22 (spider)
- added spell "Dark Sludge" to precast blacklist. Reasoning: client crash.
- fix spells/abilities of Dun Modr siege dwarves. Reasoning: their scripts were using NYI spells, I've replaced them with identical ones that are implemented
- fix placement of two books in Menethil Harbor. Reasoning: environment changes in vanilla made them float.
- fix Z placement for Hargin Mundar, Innkeeper Helbrek and Junder Brokk. Reasoning: all of them are in the inn of Menethil Harbor; seems the Inn model was changed in vanilla.
- fix Innkeeper Helbrok's inventory. Reasoning: he was assigned a non-existing inventory but his real inventory was fortunately preserved.

### CODE REVIEW

**Comment by Fluglow** [comment]
Spider trainers should be using template 275 (#774). Somewhat related, [Frank Lasson](https://db.thealphaproject.eu/index.php?action=show_creature&id=4902&filter=Frank+Lasson&sort_order=name&pos=1&max=1) is also similarly missing their trainer list. Maybe you can include that in the PR.

**Comment by geo-tp** [comment]
Regarding NPCs, the max entry for 0.5.3 has been determined here, that means all NPCs currently spawned should be part of 0.5.3 

https://github.com/The-Alpha-Project/alpha-core/issues/313

**Comment by mindphluxnet** [comment]
Yeah, about that - I'm not convinced about the "up to 5700 are 100% confirmed". Two examples:

- Phantim is 5314, why would Blizzard bother to put a single, level 62 elite dragon in an otherwise empty part of a low level area? We know the area will later house the Dragons of Nightmare but in the context of 0.5.3 alpha there's just nothing that suggests the NPC should have already been there - especially since there are no screenshots of him, at least to my knowledge. Pretty sure alpha testers would have made loads of screenshots as it's a pretty unique sight.
- Tirion Fordring is 1855 which is really low but he has no model and is standing waist-deep in the terrain. So at the very least he's not supposed to be there just yet because the placement is clearly from vanilla. The area is completely unfinished as well.

Isn't it possible some designer responsible for creating NPCs added them early because the request to make them was there but they weren't put in until after 0.5.3?

**Comment by geo-tp** [comment]
Concerning Phantim, other elite dragons are spawned as well (for example in Feralas), it could be located somewhere else but he is probably spawned.

(Some screenshot from pre release)
187035878-eeef367b-9fb2-4b73-acd9-a6d00df17c31

187035881-c693b963-226c-4b7a-aa17-095888e00516

Concerning Tirion, I don't remember a NPC with a low entry that needed to be despawned, even in a weird place.

For example : Grisha, Lanie Reed, Tharm, Syurana, Brother Anton and lot more.

All those NPC were in a weird place (Winterspring, Burning steppes, Searing gorges...) but they are all used in 0.5.3 (Lanie reed is a pet trainer, Syurana is a binder...). Probably Tirion should not stand at release position and was repurposed.


I think we should not despawn any mobs except if we have a strong evidence.
For now, I cant remember a single NPC with a low entry that was not part of 0.5.3

**Comment by mindphluxnet** [comment]
Alright, I'll remove the despawn queries.

**Comment by mindphluxnet** [comment]
I'm done with this PR.

**Comment by GrenderG** [comment]
Good job.

**Pull request merged**
