### PR TITLE
Duskwood Improvements

### PR DESCRIPTION
**Pull request by geo-tp**
Duskwood
========

About
----

In this area, a lot of npc/mobs have a really low entry (approx 200-800).
It appears that Duskwood will be updated in 0.5.4, and lot of npc/mobs will get new models.
In 0.5.3, most of them still have very old models.

Barkeep Hann
-----
Dancer_SS0410-03

Madame Eva
-----
See target frame
DwarfMageCastingBlizzard

Commandant Althea Ebonlocke 
-----

Very difficult to be sure just with this screenshot, here's more evidences

This display id seems placeholder for important female NPC, like Grand Admiral Jes Teres in SW
unknown

We can see here that Madame Eva and Commandant Althea have linked display_id and entry which reinforce this assumption.
Capture d’écran_2022-08-05_01-38-49
Capture d’écran_2022-08-05_01-41-30

Morg Gnarltree
----

On same screenshot

We can barely see a NPC, he seems to wear a black belt and black wrist. His entry and display_id make sens : Entry 226, display_id : 242.

Felicia Maline (gryphon master)
----

See target frame
Dancer_SS0409-02

Watchers
------

It appears that 166 display_id is placeholder for watchers
Capture d’écran_2022-08-05_00-43-59

Some already has unique display_id in 0.5.3, but some dont. Here's screenshot from models get updated
Capture d’écran_2022-08-05_02-36-21

I replaced watchers who miss display_id with 166.

Town Crier
-----

As Watchers, there are unused crier in database, placeholder seems to be 227 display_id.  it's also possible these unused crier was spawned in 0.5.3.
crier

I replaced town crier who miss display_id with 227.

Nefaru & Fenros
-------

There are 2 named worgen with no display id, we replace display_id with worgen models around.

Skeletal
------

There is only one Skelet model for now (except color variation), the "only bones" model doesnt exist yet. All skeletal mobs should use 200 display_id, as Skeletal warrior. Here's a screenshot of this model in Duskwood

Defias
----
(JUST SOME INFOS, NO MODIFICATION DONE FOR DEFIAS)

Defias mobs probably should use old defias models, but we dont have any infos about colors. We will see at the end a sample of Duskwood mobs push where we see some defias. Should we update it or wait for more evidences ?
081 - m9rgrec

Notes
-------

Here's a screenshot probably showing a part of Duskwood push (except some)
Capture d’écran_2022-08-05_01-12-45

We can see here : Barkeep, Madame Eva, female commandant, Worgen, skeletal, gryphon master, defias, town crier and probably more.
Missing display id still unresolved will probably use models we can see on this or near this range.

Spawn
-----

Some NPC location could be improved, for example : binder, or bardenter. Screenshots show a bit different exact location for some NPC. Should we update it ?

### CODE REVIEW

**Comment by GrenderG** [comment]
> Defias mobs probably should use old defias models, but we dont have any infos about colors. We will see at the end a sample of Duskwood mobs push where we see some defias. Should we update it or wait for more evidences ?

I'd say update them, if we find more precise evidences in the future we can always change their display_ids again.

> Some NPC location could be improved, for example : binder, or bardenter. Screenshots show a bit different exact location for some NPC. Should we update it ?

You can move them. :) But can you post a screenshot where the Binder location is shown? I think the current one is also based in a screenshot, but maybe it was older.

@geo-tp

**Comment by geo-tp** [comment]
Ah yes I understand why binder is spawned like that, you probably did because of that
U165P115T15D123778F238DT20040408140008

But there is another screenshot here
images_5584

First is before 0.5.3, last is after, so idk what spawn is the best

**Comment by GrenderG** [comment]
Indeed, you can move him @geo-tp.

**Comment by geo-tp** [comment]
Since we cant be sure about defias colors, i choose those

**Defias enchanter**
Were have an evidence showing defias caster with placeholder display_id
defias

So we use this display id for enchanter


**Defias Night blade**
Here's is no real evidence about color, but this defias model is surely part of Duskwood


**Defias Night runner**
Here's is no real evidence about color, but this defias model is surely part of Duskwood


Are we ok with that ?

**Comment by GrenderG** [comment]
I guess we can use these for now.

**Comment by geo-tp** [comment]
All changes have been made

**Pull request merged**
