### PR TITLE
Timestamp for quests and waypoints for bridgeworkers

### PR DESCRIPTION
**Pull request by geo-tp**
- Add datefield for `quest_template`
- Mark modified quests with 0.5.3 release date, the rest with 1.2 release date
- Add waypoints for bridgeworkers based on the only ss we have

### CODE REVIEW

**Comment by GrenderG** [comment]
Shouldn't the timestamp reflect the time when we updated that quest? Looks more useful imo.

**Comment by geo-tp** [comment]
> Shouldn't the timestamp reflect the time when we updated that quest? Looks more useful imo.

The goal is to be able to compare the timestamp of a db input (quest, items...) and the timestamp from a file, so during parsing we know which data is the oldest 

That means we can parse a lots of files while beeing sure that you always keep the oldest data available

**Comment by GrenderG** [comment]
I see, I understand. But sometimes it's hard to know the exact date, for example I don't think it's correct to set 0.5.3 date to all modified quests, since it's a mix of alphas and betas at this moment.

**Comment by geo-tp** [comment]
> I see, I understand. But sometimes it's hard to know the exact date, for example I don't think it's correct to set 0.5.3 date to all modified quests, since it's a mix of alphas and betas at this moment.

We will only parse timestamped file to be sure to not erase earlier data

I agree with you about 0.5.3 release date for modified quests but since we dont have any timestamp for these quests, it should be better to prevent any parsing on them by setting them to the earliest date avalaible

it will be necessary to review them by hand since we cant determine the date of the data they contains

**Comment by geo-tp** [comment]
To optimise this, we could mark with right timestamp, all modified quests that comes from WDB since we can determine the exact date

**Comment by GrenderG** [comment]
> I agree with you about 0.5.3 release date for modified quests but since we dont have any timestamp for these quests, it should be better to prevent any parsing on them by setting them to the earliest date avalaible

The issue is that not many modified quests have real values from 0.5.3 (or if they have, we haven't confirmed them). Wouldn't it be better to just set them to 01-01-1970 or something like that? Setting them to 0.5.3 date is confusing as external people can think that they are verified.

**Comment by geo-tp** [comment]
Indeed it's a good idea

Probably the best should be : 

- Mark with 0.5.3 date entries from this file
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WDB/version_3368_quests1.txt

- Mark with 0.5.5 date entries from this file
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WDB/version_3494_quests1.txt

- Mark the rest with 1970-01-01

**Comment by GrenderG** [comment]
Sounds good!

**Comment by GrenderG** [comment]
By the way, just noticed that you forgot to remove the db name in some insert statements.

**Comment by geo-tp** [comment]
done, added correct date for WDB parsed entries and rm db name

**Pull request merged**
